# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1761-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pobu/codes/pumpkin_ARMv8/working_temp/unit_test_single_port_blockram/single_port_blockram.cache/wt [current_project]
set_property parent.project_path /home/pobu/codes/pumpkin_ARMv8/working_temp/unit_test_single_port_blockram/single_port_blockram.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/pobu/codes/pumpkin_ARMv8/rtl/common/single_port_blockram.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top single_port_blockram -part xc7vx690tffg1761-1


write_checkpoint -force -noxdef single_port_blockram.dcp

catch { report_utilization -file single_port_blockram_utilization_synth.rpt -pb single_port_blockram_utilization_synth.pb }
